Repository GTestay/dapp-groupB-2019S1, pull requests merged in 2019-05, with the labels that each got.

#19 Refactor, creación de la cuenta compartida detro de la baquita crowdfunding.
  src/main/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/dominio/BaquitaCrowdFundingEvent.java
  src/main/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/dominio/SharedAccount.java
  src/test/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/dominio/BaquitaCrowdfundingTest.java
Labels: Refactor

#22 Cron para Cobrar Los Prestamos el Cinco de Cada Mes
  pom.xml
  src/main/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/dominio/Moneylender.java
  src/main/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/jobs/LoanPaymentsJob.java
  src/main/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/services/LoanPaymentsService.java
  src/main/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/triggers/LoanPaymentsTrigger.java
  src/test/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/jobs/LoanPaymentsJobTest.java
  src/test/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/services/LoanPaymentsServiceTest.java
Labels: enhancement

#24 Agregado cambios para Spring del PR Anterior.
  src/main/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/persistence/EventDao.java
  src/main/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/persistence/UserDao.java
  src/main/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/service/EventService.java
  src/main/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/webService/EventController.java
  src/test/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/service/EventServiceTest.java
  src/test/java/com/edu/unq/tpi/dapp/grupoB/Eventeando/webService/EventControllerTest.java
Labels: Refactor, duplicate
